### ISSUE TITLE
Searching for plug-in in hombridge fails

### ISSUE THREAD

**Issue by darrenmcuk** [seven-io/homebridge-sms#2]
When I try to add the plugin into homebridge through the homebridge UI it fails to find it. What am I doing wrong?

**Comment by matthiez** [comment]
Hi,
I just pushed the repository to [NPM](https://www.npmjs.com/package/homebridge-sms77-sms). Could you please try searching for it again?

**Comment by darrenmcuk** [comment]
Yep listing now
